/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/changelog': RouteRecordInfo<'/changelog', '/changelog', Record<never, never>, Record<never, never>>,
    '/settings/external': RouteRecordInfo<'/settings/external', '/settings/external', Record<never, never>, Record<never, never>>,
    '/settings/general': RouteRecordInfo<'/settings/general', '/settings/general', Record<never, never>, Record<never, never>>,
    '/settings/kick': RouteRecordInfo<'/settings/kick', '/settings/kick', Record<never, never>, Record<never, never>>,
    '/settings/twitch': RouteRecordInfo<'/settings/twitch', '/settings/twitch', Record<never, never>, Record<never, never>>,
    '/versioncheck': RouteRecordInfo<'/versioncheck', '/versioncheck', Record<never, never>, Record<never, never>>,
    '/webview/externalsource': RouteRecordInfo<'/webview/externalsource', '/webview/externalsource', Record<never, never>, Record<never, never>>,
    '/webview/kick': RouteRecordInfo<'/webview/kick', '/webview/kick', Record<never, never>, Record<never, never>>,
    '/webview/twitch': RouteRecordInfo<'/webview/twitch', '/webview/twitch', Record<never, never>, Record<never, never>>,
  }
}
