// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from '@wailsio/runtime';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from '../github.com/wailsapp/wails/v3/pkg/application/models.js';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from './internal/config/models.js';

export function CenterOnScreen(): $CancellablePromise<void> {
    return $Call.ByID(4082082385);
}

export function ConnectKick(input: string): $CancellablePromise<void> {
    return $Call.ByID(3727196235, input);
}

export function ConnectTwitch(channel: string): $CancellablePromise<void> {
    return $Call.ByID(1215296654, channel);
}

export function ConnectYouTube(input: string): $CancellablePromise<void> {
    return $Call.ByID(1847883930, input);
}

export function DisconnectKick(): $CancellablePromise<void> {
    return $Call.ByID(1101507841);
}

export function DisconnectTwitch(): $CancellablePromise<void> {
    return $Call.ByID(419249248);
}

export function DisconnectYouTube(): $CancellablePromise<void> {
    return $Call.ByID(2941614640);
}

export function ExpandForSettings(): $CancellablePromise<void> {
    return $Call.ByID(621393585);
}

export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(1200034045).then(($result: any) => {
        return $$createType1($result);
    });
}

export function OpenConfigFolder(): $CancellablePromise<void> {
    return $Call.ByID(431469111);
}

export function ResolveYouTubeVideo(input: string): $CancellablePromise<string> {
    return $Call.ByID(3831771995, input);
}

export function SaveWindowState(): $CancellablePromise<void> {
    return $Call.ByID(2713230737);
}

export function SetApp(
    app: application$0.App | null,
    win: application$0.WebviewWindow | null
): $CancellablePromise<void> {
    return $Call.ByID(4256893662, app, win);
}

export function ShrinkToChat(): $CancellablePromise<void> {
    return $Call.ByID(594383055);
}

export function ToggleVanish(): $CancellablePromise<void> {
    return $Call.ByID(1605625794);
}

export function UpdateConfig(cfg: config$0.Config | null): $CancellablePromise<void> {
    return $Call.ByID(481689322, cfg);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
