// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TwitchAuthStatus {
    "loggedIn": boolean;
    "login": string;

    /** Creates a new TwitchAuthStatus instance. */
    constructor($$source: Partial<TwitchAuthStatus> = {}) {
        if (!("loggedIn" in $$source)) {
            this["loggedIn"] = false;
        }
        if (!("login" in $$source)) {
            this["login"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TwitchAuthStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): TwitchAuthStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TwitchAuthStatus($$parsedSource as Partial<TwitchAuthStatus>);
    }
}
