// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ExpandForSettings():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function ShrinkToChat():Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
