// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ConnectKick(arg1:string):Promise<void>;

export function ConnectTwitch(arg1:string):Promise<void>;

export function ConnectYouTube(arg1:string):Promise<void>;

export function DisconnectKick():Promise<void>;

export function DisconnectTwitch():Promise<void>;

export function DisconnectYouTube():Promise<void>;

export function ExpandForSettings():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function OpenConfigFolder():Promise<void>;

export function ResolveYouTubeVideo(arg1:string):Promise<string>;

export function ShrinkToChat():Promise<void>;

export function ToggleVanish():Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
