// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectTwitch(arg1) {
  return window['go']['main']['App']['ConnectTwitch'](arg1);
}

export function ConnectYouTube(arg1) {
  return window['go']['main']['App']['ConnectYouTube'](arg1);
}

export function DisconnectTwitch() {
  return window['go']['main']['App']['DisconnectTwitch']();
}

export function DisconnectYouTube() {
  return window['go']['main']['App']['DisconnectYouTube']();
}

export function ExpandForSettings() {
  return window['go']['main']['App']['ExpandForSettings']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function ResolveYouTubeVideo(arg1) {
  return window['go']['main']['App']['ResolveYouTubeVideo'](arg1);
}

export function ShrinkToChat() {
  return window['go']['main']['App']['ShrinkToChat']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
