// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExpandForSettings() {
    return window['go']['main']['App']['ExpandForSettings']();
}

export function GetConfig() {
    return window['go']['main']['App']['GetConfig']();
}

export function ShrinkToChat() {
    return window['go']['main']['App']['ShrinkToChat']();
}

export function UpdateConfig(arg1) {
    return window['go']['main']['App']['UpdateConfig'](arg1);
}
