name: Build

on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 18

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm run lint

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 18

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm run build
