name: Build

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

  push:
    branches:
      - "**"
      - "!master"

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm run lint

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm run build
