name: Build

on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches:
      - "**"
      - "!main"

jobs:
  lint-typecheck:
    if: github.event.pull_request.draft == false && github.base_ref != 'main'
    
    runs-on: windows-latest

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint
      
      - name: typecheck
        run: pnpm typecheck
    
  build:
    if: github.event.pull_request.draft == false && github.base_ref != 'main'

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build
