name: Quick Checks

on:
  push:
    branches:
      - "**"
      - "!main"
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "frontend/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - uses: pnpm/action-setup@v5
        with:
          version: latest

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

      - run: go test ./internal/...

      - run: pnpm install --frozen-lockfile
        working-directory: frontend

      - run: wails3 generate bindings -clean=true -ts

      - run: pnpm lint
        working-directory: frontend

      - run: pnpm build
        working-directory: frontend
