name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: release artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run build-production
  
  release-mac:
    needs: release-mac

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: release artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run build-production